version: "3"
services:
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
  wallet:
    build:
      context: ./
    command: npm run dev
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    volumes:
      - ./:/src/
    restart: always
    env_file: ./.env
    depends_on:
      - mongodb
    links:
      - mongodb
